### ISSUE TITLE
Trello Roadmap link seems incorrect

### ISSUE THREAD

**Issue by siamkreative** [apirocket/documentation#3]
![image](https://user-images.githubusercontent.com/1778633/118592994-29aa3300-b7d1-11eb-96d9-7dd836fa9606.png)

The roadmap link is shown both on the main site and API documentation ([here](https://github.com/apirocket/documentation/blob/master/src/guide/README.md))

**Comment by juanmiguelguerrero** [comment]
Thanks for your feedback.

The error has been resolved.
It was a problem in the workspace configuration in Trello.
